services:
  - type: web
    name: plco-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
